name: Faucet Claim Automation

on:
  schedule:
    - cron: "*/1 * * * *"   # toutes les minutes
  workflow_dispatch:

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run claim script
        env:
          FAUCETPAY_EMAIL: ${{ secrets.FAUCETPAY_EMAIL }}
          CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}
        run: python Claim.py
